lists/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home_page, name="home"),
    path('lists/new', views.new_list, name="new_list"),
    path('lists/<int:list_id>/', views.view_list, name='view_list'),
]

superlists/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lists.urls')),
    path('admin/', admin.site.urls),
]

lists/models.py
from django.db import models
from django.urls import reverse

class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from django.http import HttpResponse

from .models import Item, List


def home_page(request):
    return render(request, "lists/home.html")

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    error = None
    
    if request.method == 'POST':
        try:
            item = Item.objects.create(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect(list_)
        except ValidationError:
            item.delete()
            error = "You can't have an empty list item"
            
    return render(request, 'lists/list.html', {'list': list_, 'error': error})

def new_list(request):
    list_ = List.objects.create()
    item = Item.objects.create(text=request.POST["item_text"], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, 'lists/home.html', {"error": error})
    return redirect(list_)

lists/templates/lists/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>To-Do lists</title>
        <link href="{% static 'lists/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'lists/css/base.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-md-offset-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        <form class="form" method="POST" action="{% block form_action %}{% endblock %}">
                            <input class="form-control" type="text"
                            id="id_new_item" name="item_text"
                            placeholder="Enter a to-do item"/>
                            {% csrf_token %}
                            {% if error %}
                                <div class="form-group has-error">
                                    <span class="help-block">{{ error }}</span>
                                </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-md-offset-3">
                    {% block table %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

lists/templates/lists/home.html
{% extends 'lists/base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

lists/templates/lists/list.html
{% extends 'lists/base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{ list.id }}/{% endblock %}
{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}